### ISSUE TITLE
Provide Developer Sandbox as VM Image

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-developer-sandbox#1]
# Background:
- We are facing the two following problems with building the script-language containers:
  - Support for Windows is unpractical, because Linux Docker on Windows is quite messy
  -  Not everyone can get a cloud VM

# Todo:
- Create VM Image with all necessary Dependencies
- Setup Build Process to keep it up to date
- Release it public available
- Link to it in Readme

# Possible solution:
- Packer
-  upload it public cloud bucket

**Comment by tkilias** [comment]
GCP image export can export into some commonly used formats, e.g. vmdk, vmdx.
Unfortunately, not into OVF/OVA. Virtualbox, KVM and Hyper-V are solved with that. Only,  VMWare we need to investigate more.

https://cloud.google.com/sdk/gcloud/reference/compute/images/export

**Comment by tkilias** [comment]
Packer and GCP: 
- https://www.packer.io/docs/builders/googlecompute/
- https://cloud.google.com/cloud-build/docs/building/build-vm-images-with-packer

**Comment by tkilias** [comment]
Depends on https://github.com/exasol/script-languages-release/issues/502

**Comment by tkilias** [comment]
Creating VM images from AWS AMI https://docs.aws.amazon.com/vm-import/latest/userguide/vmexport_image.html

**Comment by tomuben** [comment]
Boto3 also support export of VM's:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ssm.html
Also it supports remote execution of commands on the VM (see [here](https://stackoverflow.com/questions/42645196/how-to-ssh-and-run-commands-in-ec2-using-boto3) for an example). With that we could easily install the environment on a new VM which was started from an official AMI.

**Comment by tkilias** [comment]
> Boto3 also support export of VM's: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ssm.html Also it supports remote execution of commands on the VM (see [here](https://stackoverflow.com/questions/42645196/how-to-ssh-and-run-commands-in-ec2-using-boto3) for an example). With that we could easily install the environment on a new VM which was started from an official AMI.

This was the plan

**Comment by tkilias** [comment]
Our current plan:

- VM/Container creation gets orchestrated by a python project
  - create the seed EC2 instance
  - trigger the installation of the seed EC2 instance from python
  - export of the AMI from EC2 instances
  - conversion to VM Image and publishing
- using python for these steps, means we can write tests with pytest
- for the installation of the software on the EC2 instance I would suggest Ansible, because it already contains many tools for provisioning and it allows us to do from remote
- using Ansible also allows us easily to test the setup on a docker container 
- for calling Ansible from python we can use ansible-runner
- we also decided to use jupyterlab on the image and not jupyterjub, because the user management makes things unnecessary complex

**Comment by tomuben** [comment]
Splitted up this ticket by following ones:
- [ ] #2 
- [ ] #3 
- [ ] #4 
- [ ] #5 
- [ ] #7 
- [ ] #8
