### ISSUE TITLE
Start Jupyter systemd service in docker test environment

### ISSUE THREAD

**Issue by tomuben** [exasol/script-languages-developer-sandbox#11]
## Background

Currently, the systemd service cofiguration is disabled for the integration test with the Docker container.
Reason is, that systemd is not available in Docker containers. Possible workaround would be to use:
https://github.com/gdraheim/docker-systemctl-replacement

## Acceptance Criteria

The Jupyter systemd service should be configured for the docker integration test, too.

**Comment by tkilias** [comment]
I am closing this ticket, because slc-sandbox will be retired when the data-science-sandbox is ready and with data-science-sandbox we use a proper docker container. Furthermore, we test it in test_ci.py which might be slow, but doesn't need hacks.
