### ISSUE TITLE
Prepare correct user and sudo for Test Docker container

### ISSUE THREAD

**Issue by tomuben** [exasol/script-languages-developer-sandbox#13]
## Background

The Test Container in the integration test currently uses only root.
For that, all Ansible task's need to get a flag indicating if they should run with `sudo` or not, check [here](https://github.com/exasol/script-languages-developer-sandbox/blob/bb9cde551c0ad9efb06015405097efdd7338125c/exasol_script_languages_developer_sandbox/runtime/ansible/roles/docker/tasks/main.yml#L6) for one example.

If the Docker container would have the default user `ubuntu` with `sudo`, we could remove this flag.

## Acceptance Criteria

1. Create the default user `ubuntu` (similar to the user in the EC-2 instance) in the Docker Test-Container
2. Install sudo in the Docker Test-Container
3. Remove the flag `need_sudo` in all ansible scripts, and replace with `become: true`

**Comment by tkilias** [comment]
This is obsolete, because the slc-sandbox will be replaced in the future by the data-science-sandbox and there we provide a proper docker image for which we need to implement this anyway. https://github.com/exasol/data-science-sandbox/issues/66
