### ISSUE TITLE
Check if removing apt cache reduces size of the image

### ISSUE THREAD

**Issue by tomuben** [exasol/script-languages-developer-sandbox#31]
## Background

We need to update the apt cache during the setup of the EC-2 instance. Maybe we could decrease the size of the final VM files by cleaning up the apt cache at the end.

## Acceptance Criteria

Run:
```
- ansible.builtin.apt:
    clean: yes
  become: yes
```
at the end of the setup

**Comment by tkilias** [comment]
I moved this ticket to https://github.com/exasol/data-science-sandbox/issues/67, because the slc-sandbox will be retired when the data-science-sandbox is ready.
