### ISSUE TITLE
Run tests for the tutorial Jupyter notebook we provide

### ISSUE THREAD

**Issue by tomuben** [exasol/script-languages-developer-sandbox#53]
## Background

The Jupyter tutorial notebook which is preloaded is currently not tested. Any change on `exaslct` / the used flavor can cause it to break. 
We should create a automated test during the `ci-test` which leverages:
https://nbconvert.readthedocs.io/en/latest/execute_api.html
https://nbconvert.readthedocs.io/en/latest/usage.html#convert-script
to execute the test on the started EC2 instance.

## Acceptance Criteria

During the ci-test, connect to the test EC2 instance and run the jupyter file using `nbconvert`. If it fails. the ci-test should fail.

**Comment by tkilias** [comment]
Obsolete
