### ISSUE TITLE
Ansible and Python updates

### ISSUE THREAD

**Issue by MarleneKress79789** [exasol/script-languages-developer-sandbox#90]
Ansible needs to be updated to at least >= 8.0.5 for security reason, but this requires a switch to Python 3.9. Thsi the causes problems with dependency resolving, namely` importlib_resources = ">=5.4.0"` and` exasol_script_languages_release = { git = "https://github.com/exasol/script-languages-release.git", tag = "5.0.0"}` cause trouble.

**Comment by ckunki** [comment]
Too much effort, project will be archived in near future anyway
